export const PRODUCT_ACTION_TYPE = {
    // SET_PRODUCTS: "SET_PRODUCTS"
    FETCH_PRODUCTS_START:'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCESS:'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILED:'FETCH_PRODUCTS_FAILED'
}